# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=16)),
                ('host', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=1024)),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
