# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumer',
            new_name='Agent',
        ),
    ]
