# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Operation'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Agent'),
        ),
    ]
