# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0002_auto_20160720_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 19, 47, 40, 419420, tzinfo=utc)),
        ),
    ]
