# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0002_auto_20160728_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='responder',
            field=models.CharField(choices=[('SIMPLE_MOCK_RESPONDER', 'Simple Mock Responder'), ('FILTER_MOCK_RESPONDER', 'Filter Mock Responder')], default='SIMPLE_MOCK_RESPONDER', max_length=64),
        ),
    ]
