# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0003_agent_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='content_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 20, 16, 14, 571971, tzinfo=utc)),
        ),
    ]
