# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0003_operation_responder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='filter',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
