# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0004_auto_20160802_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecondition',
            name='field_type',
            field=models.CharField(choices=[('LABEL', 'Label'), ('HTTP_CODE', 'HTTP Code'), ('CONTENT', 'Content')], max_length=32),
        ),
        migrations.AlterField(
            model_name='responsecondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With')], max_length=16),
        ),
    ]
