# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0005_auto_20160802_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
