# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0006_filter_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='header_or_query_param',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='request_condition',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='response_conditions',
        ),
        migrations.AddField(
            model_name='requestcondition',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Filter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestcondition',
            name='header_or_query_param',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='responsecondition',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Filter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestcondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('CONTAINS', 'Contains'), ('STARTSWITH', 'Starts With'), ('ENDSWITH', 'Ends With'), ('REGEX', 'Regular Expression')], max_length=16),
        ),
        migrations.AlterField(
            model_name='responsecondition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('CONTAINS', 'Contains'), ('STARTSWITH', 'Starts With'), ('ENDSWITH', 'Ends With')], max_length=16),
        ),
    ]
