# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0006_auto_20160720_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mock_strategy',
            field=models.CharField(choices=[('ROUND_ROBIN', 'Round Robin')], default='ROUND_ROBIN', max_length=64),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 17, 3, 58, 163889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mockresponse',
            name='http_code',
            field=models.IntegerField(choices=[(200, 'Success'), (500, 'Error')], default=200),
        ),
    ]
