# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0007_auto_20160804_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='mockatron_interceptor.Agent'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='mockatron_interceptor.Operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mockatron_interceptor.Agent'),
        ),
        migrations.AlterField(
            model_name='requestcondition',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_conditions', to='mockatron_interceptor.Filter'),
        ),
        migrations.AlterField(
            model_name='response',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockatron_interceptor.Agent'),
        ),
        migrations.AlterField(
            model_name='response',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='mockatron_interceptor.Operation'),
        ),
        migrations.AlterField(
            model_name='responsecondition',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_conditions', to='mockatron_interceptor.Filter'),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set([('protocol', 'host', 'port', 'path', 'method')]),
        ),
    ]
