# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0007_auto_20160721_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockresponse',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 21, 27, 12, 728500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mock_strategy',
            field=models.CharField(choices=[('ROUND_ROBIN_STRATEGY', 'Round Robin')], default='ROUND_ROBIN_STRATEGY', max_length=64),
        ),
        migrations.AlterField(
            model_name='mockresponse',
            name='http_code',
            field=models.IntegerField(choices=[(200, '(200) OK'), (500, '(500) Internal Server Error'), (100, '(100) Continue'), (101, '(101) Switching Protocols'), (201, '(201) Created'), (202, '(202) Accepted'), (203, '(203) Non-Authoritative Information'), (204, '(204) No Content'), (205, '(205) Reset Content'), (206, '(206) Partial Content'), (300, '(300) Multiple Choices'), (301, '(301) Moved Permanently'), (302, '(302) Found'), (303, '(303) See Other'), (304, '(304) Not Modified'), (305, '(305) Use Proxy'), (306, '(306) (Unused)'), (307, '(307) Temporary Redirect'), (400, '(400) Bad Request'), (401, '(401) Unauthorized'), (402, '(402) Payment Required'), (403, '(403) Forbidden'), (404, '(404) Not Found'), (405, '(405) Method Not Allowed'), (406, '(406) Not Acceptable'), (407, '(407) Proxy Authentication Required'), (408, '(408) Request Timeout'), (409, '(409) Conflict'), (410, '(410) Gone'), (411, '(411) Length Required'), (412, '(412) Precondition Failed'), (413, '(413) Request Entity Too Large'), (414, '(414) Request-URI Too Long'), (415, '(415) Unsupported Media Type'), (416, '(416) Requested Range Not Satisfiable'), (417, '(417) Expectation Failed'), (501, '(501) Not Implemented'), (502, '(502) Bad Gateway'), (503, '(503) Service Unavailable'), (504, '(504) Gateway Timeout'), (505, '(505) HTTP Version Not Supported')], default=200),
        ),
    ]
