# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0008_auto_20160721_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 21, 27, 51, 268906, tzinfo=utc)),
        ),
    ]
