# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0010_auto_20160721_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='headers',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 22, 13, 38, 52, 62103, tzinfo=utc)),
        ),
    ]
