# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0011_auto_20160722_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseScriptFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('script', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 16, 0, 10, 609960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mock_strategy',
            field=models.CharField(choices=[('SIMPLE_MOCK_STRATEGY', 'Simple Mock Strategy')], default='SIMPLE_MOCK_STRATEGY', max_length=64),
        ),
        migrations.AddField(
            model_name='responsescriptfilter',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Agent'),
        ),
    ]
