# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0012_auto_20160725_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 16, 2, 51, 430564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='responsescriptfilter',
            name='script',
            field=models.TextField(),
        ),
    ]
