# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0013_auto_20160725_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('request_filter_type', models.CharField(choices=[('CONTENT', 'Content (Body)'), ('HEADER', 'HTTP Header')], max_length=32)),
                ('request_filter_operator', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('STARTS_WITH', 'Starts With'), ('NOT_STARTS_WITH', 'Not Starts With'), ('ENDS_WITH', 'Ends With'), ('NOT_ENDS_WITH', 'Not Ends With'), ('REGEX', 'Regular Expression')], max_length=16)),
                ('request_filter_value', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('STARTS_WITH', 'Starts With'), ('NOT_STARTS_WITH', 'Not Starts With'), ('ENDS_WITH', 'Ends With'), ('NOT_ENDS_WITH', 'Not Ends With'), ('REGEX', 'Regular Expression')], max_length=256)),
                ('response_filter_type', models.CharField(choices=[('LABEL', 'Label'), ('CONTENT', 'Content'), ('HTTP_CODE', 'HTTP Code')], max_length=32)),
                ('response_filter_operator', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('STARTS_WITH', 'Starts With'), ('NOT_STARTS_WITH', 'Not Starts With'), ('ENDS_WITH', 'Ends With'), ('NOT_ENDS_WITH', 'Not Ends With'), ('REGEX', 'Regular Expression')], max_length=16)),
                ('response_filter_value', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('STARTS_WITH', 'Starts With'), ('NOT_STARTS_WITH', 'Not Starts With'), ('ENDS_WITH', 'Ends With'), ('NOT_ENDS_WITH', 'Not Ends With'), ('REGEX', 'Regular Expression')], max_length=256)),
                ('header', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='responsescriptfilter',
            name='agent',
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 18, 56, 16, 476746, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ResponseScriptFilter',
        ),
        migrations.AddField(
            model_name='responsefilter',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockatron_interceptor.Agent'),
        ),
    ]
