# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0014_auto_20160725_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseFilter',
            new_name='MockFilter',
        ),
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 18, 57, 15, 961566, tzinfo=utc)),
        ),
    ]
