# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0015_auto_20160725_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 19, 8, 49, 159783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mockfilter',
            name='header',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='mockfilter',
            name='request_filter_value',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='mockfilter',
            name='response_filter_value',
            field=models.CharField(max_length=256),
        ),
    ]
