# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0017_auto_20160725_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 25, 19, 16, 3, 794499, tzinfo=utc)),
        ),
    ]
