# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mockatron_interceptor', '0019_auto_20160725_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
